# Generated by Django 5.1.3 on 2025-04-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_passcode_profile_passcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="currency_code",
            field=models.CharField(default="NGN", max_length=10),
        ),
        migrations.AddField(
            model_name="country",
            name="currency_symbol",
            field=models.CharField(default="#", max_length=5),
        ),
    ]
