# Generated by Django 5.2 on 2025-06-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_emailverificationtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetotp",
            name="otp",
            field=models.CharField(max_length=4),
        ),
    ]
