# Generated by Django 5.2.3 on 2025-06-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailySalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "total_sales_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("total_transactions", models.IntegerField(default=0)),
                ("successful_transactions", models.IntegerField(default=0)),
                ("failed_transactions", models.IntegerField(default=0)),
            ],
        ),
    ]
