# Generated by Django 5.2.3 on 2025-06-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailysalesreport",
            name="failed_transactions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dailysalesreport",
            name="successful_transactions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dailysalesreport",
            name="total_sales_amount",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=12),
        ),
        migrations.AlterField(
            model_name="dailysalesreport",
            name="total_transactions",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
