# Generated by Django 5.2.3 on 2025-06-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="tip_amount",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="tip_percentage",
        ),
        migrations.AddField(
            model_name="cart",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
