# Generated by Django 5.1.3 on 2025-06-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
